### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlin/coroutines/Continuation

### ISSUE THREAD

**Issue by sebastienvermeille** [infinum/Retromock#10]
Hi, I try to use it for a JAVA project but unfortunately it fails due to:
`java.lang.NoClassDefFoundError: kotlin/coroutines/Continuation`

seems that kotlin is somethow required to use this lib in a java project.

I could solve it by adding this dependency to my pom.xml:
```xml
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-coroutines-experimental-compat</artifactId>
            <version>1.4.32</version>
            <scope>test</scope>
        </dependency>
```

**Comment by JonatanPlesko** [comment]
Hi, sorry about the lack of responses. Adding Coroutines broke compatibility with Java which we should fix, but until we do, you should be able to use the 1.0.0 version with no issues in your project.

**Comment by antunflas** [comment]
Hi @sebastienvermeille,

could you please share the full stacktrace or at the minimum reproducible example?
I didn't manage to reproduce the problem by including the library in plain java project.

I see you managed to bypass the issue by adding dependency in the test scope. Do you have problems only in the test scope or in the main scope also?

**Comment by antunflas** [comment]
Closing as there is no feedback.
