### ISSUE TITLE
Use Retromock to create a mock build variant

### ISSUE THREAD

**Issue by llama-0** [infinum/Retromock#13]
Hi there!

Is it possible to 'switch on' Retromock annotations only in mock build variant?

Suppose you have these build variants:
- developerDebug | developerRelease
- prodDebug | prodRelease
- mockDebug | mockRelease

and you want to mock retrofit calls only for the last variant, but use real retrofit calls in developer and prod versions. How one can achieve that? Thanks in advance!

**Comment by RahulSDeshpande** [comment]
@llama-0
I was looking for the similar approach & it worked very well using mock flavor & RetroMock.

Cheers! 💃🏼

**Comment by RahulSDeshpande** [comment]
I am facing some new issue now.

I am using Retromock in one of personal apps.
I have a separate network module where all the Retrofit & Retromock inits are done.
Can someone tell me for this type of multi-variant & multiple modules project, **in which module should I place all the assets JSONs** -> `:app` or `:network`?

**Comment by antunflas** [comment]
@RahulSDeshpande

> (AFAIK, all the code & res are merged in the final APK/AAB, so it really shouldn't matter in which module the assets are, right?)

I also think it shouldn't matter. Do you experience any problem with it?

**Comment by RahulSDeshpande** [comment]
@llama-0 
Hey finally it worked, I fine-tuned the Retromock setup, and added all my api mock jsons into the `:network` module's assets folder.
Its working perfectly. 💯 
Cheers! Thanks! ❤️
