### ISSUE TITLE
Getting Null exception while reading json file

### ISSUE THREAD

**Issue by mehrozafzal** [infinum/Retromock#20]
I have followed everything as per the samples but getting Null exception while reading the json file. I am attaching code for better understanding.

   ```
 @Singleton
    @Provides
    fun provideConverterFactory(): MoshiConverterFactory =
        MoshiConverterFactory.create()

    @Singleton
    @Provides
    fun provideRetrofit(
        okHttpClient: OkHttpClient,
        moshiConverterFactory: MoshiConverterFactory
    ): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BuildConfig.BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(moshiConverterFactory)
            .build()
    }

    @Singleton
    @Provides
    fun provideRetroMock(retrofit: Retrofit): Retromock {
        return Retromock.Builder()
            .retrofit(retrofit)
            .defaultBehavior { 0 }
            .defaultBodyFactory(ResourceBodyFactory())
            .build()
    }

    @Singleton
    @Provides
    fun provideApiService(retroMock: Retromock): ApiService =
        retroMock.create(ApiService::class.java)
}
```

```
interface ApiService {
    @GET("/")
    @MockResponse(body = "/devices.json")
    @Mock
    suspend fun getDevices(): Resource<DevicesResponse>
}

 class ResourceBodyFactory : BodyFactory {
    @Throws(IOException::class)
    override fun create(input: String): InputStream {
        return FileInputStream(
            ResourceBodyFactory::class.java.classLoader.getResource(input).file
        )
    }
}
```

```
[
  {
    "Id": "1",
    "Type": "Sensor",
    "Status": "Available",
    "Price": 30999,
    "Currency": "PKR",
    "isFavorite": false,
    "imageUrl": "https://i0.wp.com/newmobiles.com.pk/wp-content/uploads/2021/06/Vivo-Y20s-new-mobiles-400x400.jpg",
    "Title": "Vivo",
    "Description": "Vivo Y20s Price in Pakistan 2022 is Rs. 30,999/-"
  },
  {
    "Id": "2",
    "Type": "Sensor",
    "Status": "Not Available",
    "Price": 24999,
    "Currency": "PKR",
    "isFavorite": false,
    "imageUrl": "https://i0.wp.com/newmobiles.com.pk/wp-content/uploads/2020/08/samsung-galaxy-m11-new-mobiles-400x400.jpg",
    "Title": "Samsung Galaxy M11",
    "Description": "Samsung Galaxy M11 Price in Pakistan is Rs. 24,999. Samsung M11 Specification includes 3GB RAM & 32GB internal storage. The New Galaxy M11 phone comes in three good looking colors of Black, Metallic Blue & Violet. The smartphone release date in Pakistan is 1st September 2020."
  }
]
```

**Comment by antunflas** [comment]
Hi @mehrozafzal ,

the only difference in comparison to [the example](https://github.com/infinum/Retromock/blob/master/samples/src/main/java/co/infinum/samples/retromock/LoadFromResource.java) is that in example `@MockResponse` annotation's body doesn't have leading `/`, so `body = "devices.json"` instead of `body = "/devices.json"`.
Could you try if that resolves your problem?

Are you implementing this in Android application perhaps? The setup in the samples in done in plain java app, so if you're implementing in Android, please follow [this section](https://github.com/infinum/Retromock#load-responses-from-android-assets).

**Comment by mehrozafzal** [comment]
@antunflas Thank you for quick response. Yes I tried without "/" and I am implementing this in Android. In the section you mentioned it is a bit unclear how to set the default Resource factory if I place my json file in resources folder.
Do I need to keep my json in assists folder or is there an option for resources folder ?

**Comment by mehrozafzal** [comment]
@antunflas just FYI I also tried pasting my json directly to body parameter instead of placing it in json file. I get this error then.
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $`

I verified that I am receiving the response in list of objects can you point what can be wrong then ?

**Comment by antunflas** [comment]
> Do I need to keep my json in assists folder or is there an option for resources folder ?

The code you use reads from Java resources directory. Is you want to read from Android's res directory you can put it inside of the `res/raw` with `context.getResources().openRawResource(id)`. Implementing body factory that does that should be similar to the body factory that reads from assets.
I prefer to use assets as you can maintain directory structure there which can be beneficial for grouping and excluding.

> I verified that I am receiving the response in list of objects can you point what can be wrong then ?

This should be out of scope of the library as converter is the one that does parsing, in your case Moshi.
I'm not sure how your model looks like, please check if
```suspend fun getDevices(): Resource<DevicesResponse>```
should be
```suspend fun getDevices(): Resource<List<DevicesResponse>>```
or you are missing some parser set to moshi that knows how to parse a list into the `Resource`.

**Comment by MehrozEmpg** [comment]
Can you post an example of fetching it from assets folder and setting the BodyFactory and Service call accordingly ? That would be helpful.

**Comment by MehrozEmpg** [comment]
@antunflas Thanks brother. Placing the file in assets worked for me well !

**Comment by mehrozafzal** [comment]
@antunflas Thanks brother. Placing the file in assets worked for me well !

**Comment by antunflas** [comment]
Cool, I'm glad it works 👍
