### ISSUE TITLE
Mock from json file - No such file or directory

### ISSUE THREAD

**Issue by dor1987** [infinum/Retromock#21]
Hi, 
I created a directory inside main with the name resources(just like in the example)
I put my json file "test.json" inside the dir
I add the    ` @MockResponse(body = "test.json")` above the suspend api call like so
`    @Mock
    @MockResponse(body = "test.json")
    @GET("/")
    suspend fun listEmployees(): Company`

When i try to run it, i get 
`file:/data/app/~~OYfJV_vd8UyH2xeGBsMSXQ==/com.example.android_test-IgYTjvD_dA-5yHt7RHQ-Rg==/base.apk!/test.json: open failed: ENOENT (No such file or directory)`

Any ideas?

**Comment by antunflas** [comment]
Hi @dor1987,

the example you followed is for Java applications. For Android application please follow [this](https://github.com/infinum/Retromock#load-responses-from-android-assets) README section and put `test.json` in the assets directory.
